# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ibkuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.AlterModelTable(
            name='ibkuser',
            table='user_accounts',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='user_profiles',
        ),
    ]
