# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161220_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verify_key',
            field=models.CharField(max_length=250, verbose_name='key'),
        ),
    ]
