# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20161220_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='key_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='key date'),
            preserve_default=False,
        ),
    ]
