# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_key_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='key_date',
            field=models.DateTimeField(auto_now=True, verbose_name='key date'),
        ),
    ]
