# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20161223_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='key_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='expire_date',
            field=models.DateTimeField(auto_now=True, verbose_name='expire date'),
        ),
    ]
