# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 02:02
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/images/gilfoyle.jpg', null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
